import { Router } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import repaymentsRouter from "./repayments.js";
import institutionsRouter from "./institutions.js";
import trustScoreRouter from "./trust-score.js";
const router = Router();
router.use("/health", healthRouter);
router.use("/auth", authRouter);
router.use("/repayments", repaymentsRouter);
router.use("/institutions", institutionsRouter);
router.use("/trust-score", trustScoreRouter);
export default router;
