import { Router } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import repaymentsRouter from "./repayments.js";
import institutionsRouter from "./institutions.js";
import trustScoreRouter from "./trust-score.js";
import profileRouter from "./profile.js";
import verificationRouter from "./verification.js";
import documentsRouter from "./documents.js";
import demoRouter from "./demo.js";
import loanProductsRouter from "./loan-products.js";
import applicationsRouter from "./applications.js";
import loansRouter from "./loans.js";
import investorRouter from "./investor.js";
import adminRouter from "./admin.js";
import loanDisbursementsRouter from "./loan-disbursements.js";
import repaymentSchedulesRouter from "./repayment-schedules.js";

const router = Router();
router.use("/health", healthRouter);
router.use("/auth", authRouter);
router.use("/repayments", repaymentsRouter);
router.use("/institutions", institutionsRouter);
router.use("/trust-score", trustScoreRouter);
router.use("/profile", profileRouter);
router.use("/verification", verificationRouter);
router.use("/documents", documentsRouter);
router.use("/demo", demoRouter);
router.use("/loan-products", loanProductsRouter);
router.use("/applications", applicationsRouter);
router.use("/loans", loansRouter);
router.use("/investor", investorRouter);
router.use("/admin", adminRouter);
router.use("/loan-disbursements", loanDisbursementsRouter);
router.use("/repayment-schedules", repaymentSchedulesRouter);

export default router;
