/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LenderRouteImport } from './routes/lender'
import { Route as MyLoansRouteImport } from './routes/my-loans'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RepaymentRouteImport } from './routes/repayment'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SystemStatesRouteImport } from './routes/system-states'
import { Route as LoansIndexRouteImport } from './routes/loans.index'
import { Route as LoansDetailsRouteImport } from './routes/loans.details'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LenderRoute = LenderRouteImport.update({
  id: '/lender',
  path: '/lender',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLoansRoute = MyLoansRouteImport.update({
  id: '/my-loans',
  path: '/my-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RepaymentRoute = RepaymentRouteImport.update({
  id: '/repayment',
  path: '/repayment',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemStatesRoute = SystemStatesRouteImport.update({
  id: '/system-states',
  path: '/system-states',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansIndexRoute = LoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansDetailsRoute = LoansDetailsRouteImport.update({
  id: '/loans/details',
  path: '/loans/details',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/applications': typeof ApplicationsRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRoute
  '/lender': typeof LenderRoute
  '/my-loans': typeof MyLoansRoute
  '/onboarding': typeof OnboardingRoute
  '/repayment': typeof RepaymentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/system-states': typeof SystemStatesRoute
  '/loans/details': typeof LoansDetailsRoute
  '/loans/': typeof LoansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/applications': typeof ApplicationsRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRoute
  '/lender': typeof LenderRoute
  '/my-loans': typeof MyLoansRoute
  '/onboarding': typeof OnboardingRoute
  '/repayment': typeof RepaymentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/system-states': typeof SystemStatesRoute
  '/loans/details': typeof LoansDetailsRoute
  '/loans': typeof LoansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/applications': typeof ApplicationsRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRoute
  '/lender': typeof LenderRoute
  '/my-loans': typeof MyLoansRoute
  '/onboarding': typeof OnboardingRoute
  '/repayment': typeof RepaymentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/system-states': typeof SystemStatesRoute
  '/loans/details': typeof LoansDetailsRoute
  '/loans/': typeof LoansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/applications'
    | '/apply'
    | '/auth'
    | '/dashboard'
    | '/learn'
    | '/lender'
    | '/my-loans'
    | '/onboarding'
    | '/repayment'
    | '/sitemap.xml'
    | '/system-states'
    | '/loans/details'
    | '/loans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/applications'
    | '/apply'
    | '/auth'
    | '/dashboard'
    | '/learn'
    | '/lender'
    | '/my-loans'
    | '/onboarding'
    | '/repayment'
    | '/sitemap.xml'
    | '/system-states'
    | '/loans/details'
    | '/loans'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/applications'
    | '/apply'
    | '/auth'
    | '/dashboard'
    | '/learn'
    | '/lender'
    | '/my-loans'
    | '/onboarding'
    | '/repayment'
    | '/sitemap.xml'
    | '/system-states'
    | '/loans/details'
    | '/loans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApplicationsRoute: typeof ApplicationsRoute
  ApplyRoute: typeof ApplyRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  LearnRoute: typeof LearnRoute
  LenderRoute: typeof LenderRoute
  MyLoansRoute: typeof MyLoansRoute
  OnboardingRoute: typeof OnboardingRoute
  RepaymentRoute: typeof RepaymentRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SystemStatesRoute: typeof SystemStatesRoute
  LoansDetailsRoute: typeof LoansDetailsRoute
  LoansIndexRoute: typeof LoansIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lender': {
      id: '/lender'
      path: '/lender'
      fullPath: '/lender'
      preLoaderRoute: typeof LenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-loans': {
      id: '/my-loans'
      path: '/my-loans'
      fullPath: '/my-loans'
      preLoaderRoute: typeof MyLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repayment': {
      id: '/repayment'
      path: '/repayment'
      fullPath: '/repayment'
      preLoaderRoute: typeof RepaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-states': {
      id: '/system-states'
      path: '/system-states'
      fullPath: '/system-states'
      preLoaderRoute: typeof SystemStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/': {
      id: '/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof LoansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/details': {
      id: '/loans/details'
      path: '/loans/details'
      fullPath: '/loans/details'
      preLoaderRoute: typeof LoansDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApplicationsRoute: ApplicationsRoute,
  ApplyRoute: ApplyRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  LearnRoute: LearnRoute,
  LenderRoute: LenderRoute,
  MyLoansRoute: MyLoansRoute,
  OnboardingRoute: OnboardingRoute,
  RepaymentRoute: RepaymentRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SystemStatesRoute: SystemStatesRoute,
  LoansDetailsRoute: LoansDetailsRoute,
  LoansIndexRoute: LoansIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
