export * as authApi from "./auth";
export * as profileApi from "./profile";
export * as documentsApi from "./documents";
export * as verificationApi from "./verification";
export * as loansApi from "./loans";
export * as applicationsApi from "./applications";
export * as investorApi from "./investor";
export * as demoApi from "./demo";
export * as adminApi from "./admin";
